0.5.0
esmero/ami pull request #152
Opened 2023-02-15 23:43 UTC by alliomeria

Changes to address https://github.com/esmero/ami/issues/151

@DiegoPino, please let me know if I missed any of the different points we discussed earlier today. Thank you!

2023-02-15 23:48 UTC, DiegoPino requested changes
Hey. Thanks! Small changes needed. Added some comments. Night! (Pikachu waves)

>

2023-02-15 23:48 UTC, DiegoPino commented on src/Entity/Controller/amiSetEntityAccessControlHandler.php
> +      case 'update':
Please keep both case statements (means don’t delete that line, the added one is good

2023-02-15 23:48 UTC, DiegoPino commented on src/Entity/Controller/amiSetEntityListBuilder.php
> +    if ($entity->access('process') && $entity->hasLinkTemplate('process-form')) {
This has some of he code i shared in the issue missing. Check that one (e,g deleteados has more checks)

2023-02-15 23:51 UTC, alliomeria commented on src/Entity/Controller/amiSetEntityAccessControlHandler.php
> +      case 'update':
Ah ok, will keep both, sorry about that. (In my local Archipelago, I only have 'update' at the moment)

2023-02-15 23:51 UTC, alliomeria commented on src/Entity/Controller/amiSetEntityListBuilder.php
> +    if ($entity->access('process') && $entity->hasLinkTemplate('process-form')) {
Got it, will update to reference your fuller changes from the main issue. Thank you!

2023-02-15 23:56 UTC, alliomeria commented
Thank you very much for your review and feedback, @DiegoPino! Do these small changes look ok now?

2023-02-16 14:09 UTC, DiegoPino requested changes
Hey! Thanks so much for addressing my review. A tiny little thing more needed (Coding Standard). Added a comment. This is the last one and we merge!

2023-02-16 14:09 UTC, DiegoPino commented on src/Entity/Controller/amiSetEntityAccessControlHandler.php
> +        case 'edit':
Hey. This is cosmetic but helps read the code (Coding Standards). Could you indent the edit and update `case` statements the same as the `case 'view'` ?

2023-02-16 14:09 UTC, DiegoPino commented on src/Entity/Controller/amiSetEntityListBuilder.php
> +      if (AmiUtilityService::checkAmiSetDeleteAdosAccess($entity) && $entity->access('deleteados') && $entity->hasLinkTemplate('delete-process-form')) {
Perfect!

2023-02-16 21:50 UTC, alliomeria commented on src/Entity/Controller/amiSetEntityAccessControlHandler.php
> +        case 'edit':
Edited--look ok now? :)

2023-02-16 21:52 UTC, DiegoPino approved these changes
Great!

2023-02-16 21:52 UTC, merged

2023-02-16 21:52 UTC, DiegoPino commented
🥳 yay! Thanks @alliomeria

2023-02-17 00:00 UTC, alliomeria commented
Thanks to you @DiegoPino!