ISSUE-161: AMI CSV export fails when an ADO has a missing type key
esmero/ami pull request #168
Opened 2023-06-07 14:53 UTC by aksm

Resolves #161.

2023-06-12 14:02 UTC, DiegoPino commented
@aksm. Since type key is one of two keys required (label/type) for an AMI set. When no type key is set, how would an AMI set from an export work? Could you please elaborate on the solution here? Thanks!

2023-06-12 14:13 UTC, aksm commented
@DiegoPino Sorry, that was silly of me. Will convert to draft and continue working on this.

2023-06-12 19:01 UTC, aksm commented
Hmm, maybe add an option to the next step to skip the row or generate the CSV only? As a user I'd want to make the decision beforehand.

> I don’t know, on one side the fix is the isset, but then after that, What would your suggestion be? An ami set without type can not be created or will be wrong. Message? Skip the row? Or generate only the csv but without an ami set + a message? What would you expect as a user?
> On Mon, Jun 12, 2023 at 8:11 PM Albert Min ***@***.***> wrote: @DiegoPino <https://github.com/DiegoPino> So is the idea to log it and return an empty row? throw an exception? something else? — Reply to this email directly, view it on GitHub <[#168 (comment)](https://github.com/esmero/ami/pull/168#issuecomment-1587833761)>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ABU7ZZZCYLN3EEUE5JX4KPTXK5LW5ANCNFSM6AAAAAAY576EF4> . You are receiving this because you were mentioned.Message ID: ***@***.***>
> -- Diego Pino Navarro Digital Repositories Developer Metropolitan New York Library Council (METRO)

2023-06-15 17:43 UTC, DiegoPino requested changes
Better to use ($this->context which is local to this batch) instead of tempstore (which is global to this user, specially when no batch aware id is passed)

2023-06-15 17:43 UTC, DiegoPino commented on src/Plugin/Action/AmiStrawberryfieldCSVexport.php
> +      if ($file_id && $this->configuration['create_ami_set'] && $this->tempStore->get('ado_type_exists')) {
@aksm almost (logic seems good). You should not use tempStore like this. The tempStore (this one) is global for a logged in user, and even if you are resetting the value on a new fetch, because you are not giving it a specific name there could be race conditions where this ado_type_exists might end being set (for 6 days) for ado_type_exist == FALSE or two Exports are running at the same time for the same user (we can't control what users do).

See for example how I used it in the saveRows function  $this->tempStore->set($this->getCid(), $rows).
I feel it easier/less permanent to use `$this->context` to pass variable data around during a batch. It is not saved in the DB as permanent and it lives only during the actual batch. 
Said differently: temp store is not a good fit for a flag in this case, please use $this->context to flag ado_type_exists. Thanks

2023-06-15 17:47 UTC, aksm commented on src/Plugin/Action/AmiStrawberryfieldCSVexport.php
> +      if ($file_id && $this->configuration['create_ami_set'] && $this->tempStore->get('ado_type_exists')) {
Ah ok, that makes sense. Will update. Thanks.

2023-06-15 19:14 UTC, DiegoPino commented
@aksm did you test this? Could you provide information on how this was tested? Thanks

2023-06-15 19:27 UTC, aksm commented
@DiegoPino Yes, I tested by selecting different combinations of ADOs, e.g.:

* 1 ADO with no type key
* Multiple ADOs that included one without the type key
* Multiple ADOs all with type keys

Then I processed with and without the new AMI set option to see that it properly produced the CSV and skipped the AMI set if there's a type missing on any ADOs and gave the user a message.

> @aksm did you test this? Could you provide information on how this was tested? Thanks

2023-06-15 19:30 UTC, merged