ISSUE-67 --> 0.3.0
esmero/ami pull request #68
Opened 2022-03-15 21:44 UTC by patdunlavey

# What this does
- Adds access checks for AMI Set delete processed ADOs operation (with caching for performance). If an AMI set's operation is 'update' or 'patch', do not show "Delete processed ADOs in the amiset/list operations column, and do not show the "Delete Processed ADO's" link when viewing an individual AMI Set.
- Make delete processed form always return a correctly formed drupal form (though I don't think we will ever see this version of the form now, so maybe we should just delete this part of the buildForm function).

See [ISSUE-67](https://github.com/esmero/ami/issues/67).

2022-03-15 21:47 UTC, DiegoPino commented on src/Form/amiSetEntityDeleteProcessedForm.php
> +        $form = $form + parent::buildForm($form, $form_state);
Nice!

2022-03-15 21:50 UTC, DiegoPino commented on src/AmiUtilityService.php
> +      if ($deleteados_access_cache = \Drupal::cache()->get($cache_id)) {
You can also use  `use UseCacheBackendTrait;` to avoid calling the static container here...

2022-03-15 21:50 UTC, DiegoPino commented on ami.module
> +function ami_entity_update(Drupal\Core\Entity\EntityInterface $entity) {
Is the cache liberated if an AMI set is deleted?

2022-03-15 21:51 UTC, DiegoPino commented on src/AmiUtilityService.php
> +      if ($deleteados_access_cache = \Drupal::cache()->get($cache_id)) {
Or not... because this is static? i Wonder... but the code looks good to me... do we need this function anywhere else?

2022-03-15 21:56 UTC, DiegoPino commented on src/Entity/Controller/amiSetEntityAccessControlHandler.php
> +    if($operation == 'deleteados') {
Wonder (since you are here) we (sorry maybe?) check also IF it even exist (operation) in case someone gets creative and puts a wrong value also for process?? Too much?

2022-03-16 13:12 UTC, patdunlavey commented on src/Entity/Controller/amiSetEntityAccessControlHandler.php
> +    if($operation == 'deleteados') {
$operation is a required argument, so it exists. No? Using non-strict comparison ('==' vs. '===') is also fine, I think. I'm not sure what you're getting at.

2022-03-16 13:28 UTC, DiegoPino commented on src/Entity/Controller/amiSetEntityAccessControlHandler.php
> +    if($operation == 'deleteados') {
No, that is not my comment. What I'm trying to say is that checking ALSO if the AMI set is well formed for that value e.g `in ['create','update','patch'] using maybe a class level constant (which we can the reuse here https://github.com/esmero/ami/blob/0bc76be41c19ecfcbec02959d7a0329b1ebe6468/src/Plugin/ImporterAdapterBase.php#L103-L107 and here https://github.com/esmero/ami/blob/0bc76be41c19ecfcbec02959d7a0329b1ebe6468/src/Form/amiSetEntityReconcileForm.php#L106-L110 would be nice to avoid showing e.g PROCESS if someone decided it was a good idea to put some random value manually into an AMI set...

Just forget it, I can do that another time

2022-03-16 13:58 UTC, patdunlavey commented on ami.module
> +function ami_entity_update(Drupal\Core\Entity\EntityInterface $entity) {
I added hook_entity_delete.

2022-03-18 16:40 UTC, patdunlavey commented on ami.module
> +function ami_entity_update(Drupal\Core\Entity\EntityInterface $entity) {
@DiegoPino ok to resolve this?

2022-03-28 13:50 UTC, DiegoPino requested changes
Small change needed to deal with manual update of the Operation type via direct edit of the JSON

2022-03-28 15:07 UTC, patdunlavey commented on ami.module
> +    AmiUtilityService::invalidateAmiSetDeleteAdosAccessCache($entity);
Thanks for the catch. I'll try to get this done in the next day or two.

2022-03-28 15:12 UTC, DiegoPino commented on ami.module
> +    AmiUtilityService::invalidateAmiSetDeleteAdosAccessCache($entity);
Thanks @patdunlavey

2022-03-28 16:30 UTC, patdunlavey commented on ami.module
> +    AmiUtilityService::invalidateAmiSetDeleteAdosAccessCache($entity);
I'm a bit confused @DiegoPino . The call to AmiUtilityService::invalidateAmiSetDeleteAdosAccessCache($entity); happens every time an AMI Set is updated or deleted. That would include manual edits to the AMI set json. (There's no need to do it when an AMI Set is created, since there's no cache entry yet.) Are you suggesting that invalidating the cache is not adequate - that it must immediately be cleared? Or are you thinking that someone might edit the json through some other means that doesn't trigger the entity_update or delete hook?

2022-03-28 16:38 UTC, DiegoPino commented on ami.module
> +    AmiUtilityService::invalidateAmiSetDeleteAdosAccessCache($entity);
Gosh, I was testing your code pre-hook.... 😶‍🌫️ will fetch again and re-test... sorry!

2022-04-15 21:26 UTC, DiegoPino approved these changes
All good. Will merge against 0.4.0. And retest just to be sure I did not break anything while moving with versions up related to this

2022-04-15 21:28 UTC, merged